name: connect to ec2
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: change permissions
        run: chmod 400 workflow2/myinstance.pem
    
    
