name: Deploy to Amazon ECSs

on: workflow_dispatch


permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRETE_KEY }}
        aws-region: us-east-1
        
    - name: intializing terraform
      run: terraform init
    - name: plan
      run: terraform plan
    - name: building terraform
      run: terraform apply -auto-approve
    - name: build docker image
      run: docker build -t madhavpreeth123/myimg .
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build -t myimage .
    - name: Tag the image
      run: |
        docker tag myimage madhavpreeth123/myimage
    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Push the image
      run: |
        docker push madhavpreeth123/myimage
    - name: fetching image from dockerhub
      run: docker pull madhavpreeth123/myimage
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{secrets.AWS_SECRETE_KEY}}
        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: build
      run: docker build -t madhav .
    - name: tag
      run: docker tag my_first:latest public.ecr.aws/w5q0r1u0/my_first:latest
    - name: push
      run: docker push public.ecr.aws/w5q0r1u0/my_first:latest



